### ISSUE TITLE
Error after npm run develop

### ISSUE THREAD

**Issue by JaosnHsieh** [vladotesanovic/angular2-express-starter#12]
OS: Windows 7
node version: v4.4.7
npm version: v2.15.8

I followed the commands,
git clone https://github.com/vladotesanovic/angular2-express-starter
cd angular2-express-starter
npm install
npm run develop

and it shows errors
` module.js:327
     throw err;
     ^

 Error: Cannot find module 'debug'
     at Function.Module._resolveFilename (module.js:325:15)
     at Function.Module._load (module.js:276:25)
     at Module.require (module.js:353:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (C:\node\angular2-express-starter\server\bin\www:8
)
     at Module._compile (module.js:409:26)
     at Object.Module._extensions..js (module.js:416:10)
     at Module.load (module.js:343:32)
     at Function.Module._load (module.js:300:12)
     at Function.Module.runMain (module.js:441:10)`

**Comment by mkonars** [comment]
Hi, you can run "npm install debug --save" to fix this. I have created a pull request to add this dependency

**Comment by vladotesanovic** [comment]
@mkonars tnx :+1:

**Comment by JaosnHsieh** [comment]
It worked for me. Thanks !!
