### ISSUE TITLE
npm run develop failed

### ISSUE THREAD

**Issue by BaroqueCoding** [vladotesanovic/angular2-express-starter#17]
OS X 10.11.6
node -v 5.12.0
npm -v 3.8.6

At first, I got command not found error message

`sh: concurrently: command not found`
after I install concurrently package,  I got another one.

Error occured when executing command: nodemon ./server/bin/www
 Error: spawn nodemon ENOENT
     at exports._errnoException (util.js:893:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
     at onErrorNT (internal/child_process.js:348:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Function.Module.runMain (module.js:449:11)
     at startup (node.js:148:18)
     at node.js:405:3

**Comment by vladotesanovic** [comment]
Can you try again with:

``` bash
npm install
```

if that does not fix, can you try to execute:

``` bash
npm install concurrently
```

**Comment by BaroqueCoding** [comment]
command not found error(concurrently) solved but nodemon error doesn't.

**Comment by chapm250** [comment]
Are you running on fedora? I am having the same issue and it said that my OS was not compatable with fsevents@1.0.14
