### ISSUE TITLE
ES6 targetting breaks the project?

### ISSUE THREAD

**Issue by georgeedwards** [vladotesanovic/angular2-express-starter#32]
I am trying to add an additional dependency to this starter project. 
If I run:

```
npm i mongoose --save
npm i @types/mongoose -save
```

then I get the following issues when I run tsc on the project

> node_modules/@types/mongodb/index.d.ts(1216,16): error TS2304: Cannot find name 'Promise'.

despite the exclude `node_modules` feature of the package.json 

Why is this and is there a workaround?

**Comment by vladotesanovic** [comment]
Hm i am not sure what problem you have, but did you save that @type/mongoose ?

I do everything as you did:

``` bash
npm i mongoose --save
npm i @types/mongoose --save
```

tried with 

``` javascript
import * as mongoose from "mongoose";
console.log(mongoose);
```

Everything works

**Comment by georgeedwards** [comment]
@vladotesanovic I have just removed both npm packages and run the app (it crashes as expected). The I copied and ran those two commands one by one in the project root and I get loads of these:

```
[0] node_modules/@types/mongodb/index.d.ts(17,64): error TS2304: Cannot find name 'Promise'.
[0] node_modules/@types/mongodb/index.d.ts(21,57): error TS2304: Cannot find name 'Promise'.
[0] node_modules/@types/mongodb/index.d.ts(165,78): error TS2304: Cannot find name 'Promise'.
[0] node_modules/@types/mongodb/index.d.ts(171,92): error TS2304: Cannot find name 'Promise'.
[0] node_modules/@types/mongodb/index.d.ts(175,34): error TS2304: Cannot find name 'Promise'.
[0] node_modules/@types/mongodb/index.d.ts(182,20): error TS2304: Cannot find name 'Promise'.
[0] node_modules/@types/mongodb/index.d.ts(186,86): error TS2304: Cannot find name 'Promise'.
```

**Comment by digital216** [comment]
@georgeedwards Do you have the definitions for one of the promises installed?  i.e. core-js or es6-promise?

**Comment by georgeedwards** [comment]
@digital216 Yes, I have added that now and the issue has gone away. However, in the process of finding that, I have found a quite interesting issue. 

I have copied much of the code into this starter from an existing project I was working on. Which is why I was surprised at getting these errors which I wasn't seeing before. The difference was that my original project TS was targeting `es6`. So I initially changed the **tsconfig.json** s to target `es6` but that broke the bundle script e.g.:

```
$ npm run bundle:prod

> Nativescript_Docs@1.0.0 bundle:prod /Users/georgeedwards/source/repos/docs
> node tools/builder.js --prod

Unhandled rejection Error: SyntaxError: Unexpected token: name (AppComponent) (line: 16806, col: 33, pos: 691022)

Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2092:9)
    at token_error (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2100:9)
    at unexpected (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2106:9)
    at semicolon (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2126:56)
    at simple_statement (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2317:73)
    at eval (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2186:19)
    at eval (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2139:24)
    at block_ (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2432:20)
    at eval (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2404:25)
    at function_ (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2410:15)
    at expr_atom (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2625:24)
    at maybe_unary (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2795:19)
    at expr_ops (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2830:24)
    at maybe_conditional (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2835:20)
    at maybe_assign (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2859:20)
    at expression (eval at <anonymous> (/Users/georgeedwards/source/repos/docs/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2878:20)
    at minify (/Users/georgeedwards/source/repos/docs/node_modules/systemjs-builder/lib/output.js:79:11)
    at exports.writeOutputs (/Users/georgeedwards/source/repos/docs/node_modules/systemjs-builder/lib/output.js:153:14)
    at /Users/georgeedwards/source/repos/docs/node_modules/systemjs-builder/lib/builder.js:805:14
    at tryCatcher (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/georgeedwards/source/repos/docs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```
