### ISSUE TITLE
Cannot find module 'reflect-metadata'

### ISSUE THREAD

**Issue by dimasjt** [vladotesanovic/angular2-express-starter#36]
when running **npm run start**

```
> angular2-express-starter@1.0.0 start /home/dimas/dimas/nodejs/angular2-express-starter
> ng serve & npm run _server

> angular2-express-starter@1.0.0 _server /home/dimas/dimas/nodejs/angular2-express-starter
> tsc -p ./server && concurrently "tsc -w -p ./server" "nodemon dist/server/bin/www.js" 

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bocistudio/Dimas/nodejs/angular2-express-starter/node_modules/angular-cli/node_modules/@ngtools/webpack/src/index.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bocistudio/Dimas/nodejs/angular2-express-starter/node_modules/angular-cli/models/webpack-build-typescript.js:5:17)
```

**Comment by vladotesanovic** [comment]
Are you still getting this error?

Can you remove node_modules and run install again?
