### ISSUE TITLE
Could not complete npm install on AWS server

### ISSUE THREAD

**Issue by jaskiratr** [vladotesanovic/angular2-express-starter#40]
```
> angular2-express-starter@1.0.0 postinstall /home/ec2-user/angular
> npm run build


> angular2-express-starter@1.0.0 build /home/ec2-user/angular
> ng build --prod --output-path=dist/client && npm run _server:build

module.js:442
    throw err;
    ^

Error: Cannot find module './_baseIteratee'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/angular/node_modules/angular-cli/node_modules/lodash/_createFind.js:1:82)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Linux 4.4.16-27.56.amzn1.x86_64
npm ERR! argv "/home/ec2-user/.nvm/versions/node/v6.2.2/bin/node" "/home/ec2-user/angular/node_modules/.bin/npm" "run" "build"
npm ERR! node v6.2.2
npm ERR! npm  v2.14.21
npm ERR! code ELIFECYCLE
npm ERR! angular2-express-starter@1.0.0 build: `ng build --prod --output-path=dist/client && npm run _server:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-express-starter@1.0.0 build script 'ng build --prod --output-path=dist/client && npm run _server:build'.
npm ERR! This is most likely a problem with the angular2-express-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod --output-path=dist/client && npm run _server:build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-express-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-express-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/angular/npm-debug.log

npm WARN optional Skipping failed optional dependency /angular-cli/webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN optional Skipping failed optional dependency /angular-cli/webpack-dev-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN optional Skipping failed optional dependency /nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm ERR! Linux 4.4.16-27.56.amzn1.x86_64
npm ERR! argv "/home/ec2-user/.nvm/versions/node/v6.2.2/bin/node" "/home/ec2-user/.nvm/versions/node/v6.2.2/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-express-starter@1.0.0 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-express-starter@1.0.0 postinstall script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-express-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-express-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-express-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/angular/npm-debug.log
```

**Comment by vladotesanovic** [comment]
It seams that this is angular-cli problem with npm. Can you use different version of node and npm on your server?

https://github.com/angular/angular-cli/issues/1041
https://github.com/angular/angular-cli/pull/1250

**Comment by jaskiratr** [comment]
Ah! I see. 
Thanks for sharing the links. I'll look into it.
