### ISSUE TITLE
when I have running 'npm develop' I have got error message

### ISSUE THREAD

**Issue by chifangjang** [vladotesanovic/angular2-express-starter#5]
when I have running *_'npm develop' *_
Please see the error message I am getting below

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, faq,
    get, help, help-search, i, init, install, install-test, it,
    link, list, ln, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/zhangqifang/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.8.3 /Users/zhangqifang/.nvm/versions/node/v5.10.1/lib/node_modules/npm

**Comment by huahouye** [comment]
In package.json file change this line 
**"develop": "concurrently \"tsc -w -p ./server\" \"tsc -w -p ./client\" \"nodemon ./server/bin/www\" ",** 
to 
**"start": "concurrently \"tsc -w -p ./server\" \"tsc -w -p ./client\" \"nodemon ./server/bin/www\" ",** (change the word '**develop**' to '**start**'),then run 'npm start' , this work for me.

**Comment by chifangjang** [comment]
thank @huahouye 
when I trying run 'npm start'  I get the error below

GET /assets/js/app/components/home.html 500 3.857 ms - 1450
[2] Error: Not Found

**Comment by ykoehler** [comment]
try 'npm run develop'

yet, for me it crash with

[2] module.js:327
[2]     throw err;
[2]     ^
[2] 
[2] Error: Cannot find module 'debug'
[2]     at Function.Module._resolveFilename (module.js:325:15)
[2]     at Function.Module._load (module.js:276:25)
[2]     at Module.require (module.js:353:17)
[2]     at require (internal/module.js:12:17)
[2]     at Object.<anonymous> (/home/ykoehler/work/web/angular2-express-starter/server/bin/www:8:13)
[2]     at Module._compile (module.js:409:26)
[2]     at Object.Module._extensions..js (module.js:416:10)
[2]     at Module.load (module.js:343:32)
[2]     at Function.Module._load (module.js:300:12)
[2]     at Function.Module.runMain (module.js:441:10)
[2] [nodemon] app crashed - waiting for file changes before starting...

**Comment by jrgleason** [comment]
I agree @ykoehler that fixed it for me too

**Comment by vladotesanovic** [comment]
Check new update, all problems are fixed now.

ngSemantic is not updated yet, hopefully it will be done by tomorrow.
