### ISSUE TITLE
Tests don't run

### ISSUE THREAD

**Issue by JanezStupar** [vladotesanovic/angular2-express-starter#50]
I have a problem getting this starter to work fully. In particular the provided tests do not seem to run.

This is the output to stdout:

```
➜  angular2-express-starter git:(master) npm run test                        

> angular2-express-starter@1.0.0 test /tmp/angular2-express-starter
> ng test --watch=false

01 01 2017 18:48:58.859:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
01 01 2017 18:48:58.861:INFO [launcher]: Launching browser Chrome with unlimited concurrency
01 01 2017 18:48:58.868:INFO [launcher]: Starting browser Chrome
01 01 2017 18:48:59.913:INFO [Chrome 55.0.2883 (Linux 0.0.0)]: Connected on socket /#cQ8YHdvR_KMaAUgSAAAA with id 74600633
Chrome 55.0.2883 (Linux 0.0.0): Executed 0 of 0 ERROR (0.008 secs / 0 secs)

npm ERR! Linux 4.8.13-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-express-starter@1.0.0 test: `ng test --watch=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-express-starter@1.0.0 test script 'ng test --watch=false'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-express-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng test --watch=false
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-express-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-express-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/angular2-express-starter/npm-debug.log
```

Output of npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@4.0.5
3 info using node@v7.3.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle angular2-express-starter@1.0.0~pretest: angular2-express-starter@1.0.0
6 silly lifecycle angular2-express-starter@1.0.0~pretest: no script for pretest, continuing
7 info lifecycle angular2-express-starter@1.0.0~test: angular2-express-starter@1.0.0
8 verbose lifecycle angular2-express-starter@1.0.0~test: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-express-starter@1.0.0~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/tmp/angular2-express-starter/node_modules/.bin:/home/janez/bin:/usr/local/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle angular2-express-starter@1.0.0~test: CWD: /tmp/angular2-express-starter
11 silly lifecycle angular2-express-starter@1.0.0~test: Args: [ '-c', 'ng test --watch=false' ]
12 silly lifecycle angular2-express-starter@1.0.0~test: Returned: code: 1  signal: null
13 info lifecycle angular2-express-starter@1.0.0~test: Failed to exec test script
14 verbose stack Error: angular2-express-starter@1.0.0 test: `ng test --watch=false`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-express-starter@1.0.0
16 verbose cwd /tmp/angular2-express-starter
17 error Linux 4.8.13-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
19 error node v7.3.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error angular2-express-starter@1.0.0 test: `ng test --watch=false`
22 error Exit status 1
23 error Failed at the angular2-express-starter@1.0.0 test script 'ng test --watch=false'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-express-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng test --watch=false
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-express-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-express-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I suspect it has something to do with my local environment. But I have no idea how to go about debugging this problem as I am not that familiar with the current setup.

**Comment by JanezStupar** [comment]
I can confirm that this fix solves the issue. Thanks a lot Vlado!
