### ISSUE TITLE
default install/build ends in with errors

### ISSUE THREAD

**Issue by pdestrais** [vladotesanovic/angular2-express-starter#59]
Hi,

I just downloaded and installed angular2-express-starter using npm install.
The build process ends in an error
`> npm run build

> angular2-express-starter@1.0.0 build /Users/pdestrais/Projects/angular2-express-starter-master
> ng build --prod --sm=false --aot=true --output-path=dist/client && npm run _server:build

/Users/pdestrais/Projects/angular2-express-starter-master/node_modules/@ngtools/json-schema/src/schema-class-factory.js:33
            result.push(...indices);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/pdestrais/Projects/angular2-express-starter-master/node_modules/@ngtools/json-schema/src/index.js:2:30)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
`

I tried with --aot=false without success.

Any support to fix this will be greatly appreciated.

**Comment by pdestrais** [comment]
It was a problem with ng that required an update of nodejs (and typescript had to be set to version 2.1.3). This issue can be closed
