### ISSUE TITLE
ERROR at first npm run start

### ISSUE THREAD

**Issue by high-malloy** [vladotesanovic/angular2-express-starter#81]
I am getting the following error message at first 'npm run start' (direct after npm install): 

*********************************************************
[0]
[0] > angular2-express-starter@1.0.0 _server:run C:\Daten\angular2-express-starter
[0] > tsc -p ./server && concurrently "tsc -w -p ./server" "nodemon dist/server/bin/www.js"
[0]
[0] [1] [nodemon] 1.11.0
[0] [1] [nodemon] to restart at any time, enter `rs`
[0] [1] [nodemon] watching: dist/server
[0] [1] [nodemon] starting `node dist/server/bin/www.js server/app.js`
[0] [1] module.js:471
[0] [1]     throw err;
[0] [1]     ^
[0] [1]
[0] [1] Error: Cannot find module 'C:\Daten\angular2-express-starter\dist\server\bin\www.js'
[0] [1]     at Function.Module._resolveFilename (module.js:469:15)
[0] [1]     at Function.Module._load (module.js:417:25)
[0] [1]     at Module.runMain (module.js:604:10)
[0] [1]     at run (bootstrap_node.js:389:7)
[0] [1]     at startup (bootstrap_node.js:149:9)
[0] [1]     at bootstrap_node.js:504:3
[0] [1] [nodemon] app crashed - waiting for file changes before starting...
[1] ** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
[0] [0] 11:46:10 - Compilation complete. Watching for file changes.
[0] [0]
[0] [0]
[1] Hash: e0ecc507621bb8b316d6
[1] Time: 13529ms
[1] chunk    {0} 0.chunk.js, 0.chunk.js.map (common) 16.8 kB {1} {2} {3} {4} {5} {6} [rendered]
[1] chunk    {1} 1.chunk.js, 1.chunk.js.map 59.6 kB {2} {3} {5} [rendered]
[1] chunk    {2} 2.chunk.js, 2.chunk.js.map 20.7 kB {1} {3} {5} [rendered]
[1] chunk    {3} 3.chunk.js, 3.chunk.js.map 27.6 kB {1} {2} {5} [rendered]
[1] chunk    {4} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 254 kB {8} [initial] [rendered]
[1] chunk    {5} main.bundle.js, main.bundle.js.map (main) 55 kB {7} [initial] [rendered]
[1] chunk    {6} styles.bundle.js, styles.bundle.js.map (styles) 21 kB {8} [initial] [rendered]
[1] chunk    {7} vendor.bundle.js, vendor.bundle.js.map (vendor) 1.87 MB [initial] [rendered]
[1] chunk    {8} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
[1] webpack: Compiled successfully.
************************************************

**Comment by high-malloy** [comment]
types were missing.....

**Comment by raimens** [comment]
Hi I'm having the same problem, how did you solve it? which types?
